
-- Add 50 different types of desserts to the menu
INSERT INTO menu_items (name_uz, name_en, name_ru, description_uz, description_en, description_ru, price, category, image, rating, is_active) VALUES

-- Traditional Uzbek Desserts (10 items)
('Halva', 'Traditional Halva', 'Традиционная халва', 'An''anaviy o''zbek halvasi, yong''oq va shakar bilan', 'Traditional Uzbek halva with nuts and sugar', 'Традиционная узбекская халва с орехами и сахаром', 8.50, 'desserts', 'https://images.unsplash.com/photo-1551024506-0bccd828d307', 4.7, true),
('Chak-chak', 'Honey Chak-Chak', 'Чак-чак медовый', 'Asal bilan to''ldirilgan shirinlik', 'Sweet pastry filled with honey', 'Сладкая выпечка с медом', 9.00, 'desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 4.6, true),
('Navvot', 'Crystal Sugar Candy', 'Кристаллический сахар', 'Kristal shakar shaklidagi shirinlik', 'Crystal sugar candy', 'Конфеты из кристаллического сахара', 6.50, 'desserts', 'https://images.unsplash.com/photo-1548907040-4baa42d10919', 4.4, true),
('Nisholda', 'Whipped Egg White Dessert', 'Взбитый белковый десерт', 'Tuxum oqi va shakar bilan tayyorlangan', 'Made with whipped egg whites and sugar', 'Приготовлено из взбитых белков и сахара', 7.00, 'desserts', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', 4.5, true),
('Sumalak', 'Traditional Spring Dessert', 'Традиционный весенний десерт', 'Bahorda tayyorlanadigan an''anaviy shirinlik', 'Traditional spring dessert made from wheat', 'Традиционный весенний десерт из пшеницы', 12.00, 'desserts', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187', 4.8, true),
('Bodom halvasi', 'Almond Halva', 'Миндальная халва', 'Bodom bilan tayyorlangan halva', 'Halva made with almonds', 'Халва приготовленная с миндалем', 10.50, 'desserts', 'https://images.unsplash.com/photo-1551024506-0bccd828d307', 4.6, true),
('Yong''oq halvasi', 'Walnut Halva', 'Ореховая халва', 'Yong''oq bilan boy halva', 'Rich walva with walnuts', 'Богатая халва с грецкими орехами', 11.00, 'desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 4.7, true),
('Shakar plov', 'Sweet Rice Dessert', 'Сладкий рисовый десерт', 'Shakar va yog'' bilan tayyorlangan guruch', 'Rice cooked with sugar and oil', 'Рис приготовленный с сахаром и маслом', 8.00, 'desserts', 'https://images.unsplash.com/photo-1548907040-4baa42d10919', 4.3, true),
('Qaymoqli non', 'Cream Bread Dessert', 'Хлебный десерт со сливками', 'Qaymoq bilan xizmat qilinadigan shirinlik', 'Sweet bread served with cream', 'Сладкий хлеб подается со сливками', 9.50, 'desserts', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', 4.4, true),
('Mayiz', 'Raisin Sweet', 'Изюмные сладости', 'Quritilgan uzum bilan shirinlik', 'Sweet treat with dried grapes', 'Сладкое лакомство с сушеным виноградом', 7.50, 'desserts', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187', 4.2, true),

-- International Cakes (15 items)
('Shokoladli biskvit', 'Chocolate Sponge Cake', 'Шоколадный бисквит', 'Yumshoq shokoladli biskvit tort', 'Soft chocolate sponge cake', 'Мягкий шоколадный бисквитный торт', 14.00, 'desserts', 'https://images.unsplash.com/photo-1551024506-0bccd828d307', 4.8, true),
('Qulupnayli tort', 'Strawberry Cake', 'Клубничный торт', 'Yangi qulupnay bilan tayyorlangan tort', 'Fresh strawberry cake', 'Свежий клубничный торт', 16.00, 'desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 4.9, true),
('Karamel tort', 'Caramel Cake', 'Карамельный торт', 'Shirin karamel bilan qoplangan tort', 'Cake covered with sweet caramel', 'Торт покрытый сладкой карамелью', 15.50, 'desserts', 'https://images.unsplash.com/photo-1548907040-4baa42d10919', 4.7, true),
('Vanil tort', 'Vanilla Cake', 'Ванильный торт', 'Klassik vanil ta''mli tort', 'Classic vanilla flavored cake', 'Классический торт с ванильным вкусом', 13.00, 'desserts', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', 4.5, true),
('Qora shokoladli tort', 'Dark Chocolate Cake', 'Торт из темного шоколада', 'Qora shokolad bilan boy tort', 'Rich dark chocolate cake', 'Богатый торт из темного шоколада', 17.00, 'desserts', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187', 4.8, true),
('Limonli tort', 'Lemon Cake', 'Лимонный торт', 'Yangi limon ta''mi bilan tort', 'Fresh lemon flavored cake', 'Свежий лимонный торт', 14.50, 'desserts', 'https://images.unsplash.com/photo-1551024506-0bccd828d307', 4.6, true),
('Krem tort', 'Cream Cake', 'Кремовый торт', 'Kremli qatlamlar bilan tort', 'Layered cake with cream', 'Слоеный торт с кремом', 15.00, 'desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 4.7, true),
('Mevali tort', 'Fruit Cake', 'Фруктовый торт', 'Turli mevalar bilan bezatilgan tort', 'Cake decorated with various fruits', 'Торт украшенный различными фруктами', 16.50, 'desserts', 'https://images.unsplash.com/photo-1548907040-4baa42d10919', 4.8, true),
('Kok tort', 'Coconut Cake', 'Кокосовый торт', 'Kokos bilan tayyorlangan tort', 'Cake made with coconut', 'Торт приготовленный с кокосом', 14.00, 'desserts', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', 4.5, true),
('Banan tort', 'Banana Cake', 'Банановый торт', 'Pishgan banan bilan shirinlik', 'Sweet cake with ripe bananas', 'Сладкий торт со спелыми бананами', 13.50, 'desserts', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187', 4.4, true),
('Ananas tort', 'Pineapple Cake', 'Ананасовый торт', 'Tropik ananas ta''mi bilan tort', 'Tropical pineapple flavored cake', 'Тропический ананасовый торт', 15.50, 'desserts', 'https://images.unsplash.com/photo-1551024506-0bccd828d307', 4.6, true),
('Shokoladli mus', 'Chocolate Mousse Cake', 'Торт шоколадный мусс', 'Yengil shokoladli mus tort', 'Light chocolate mousse cake', 'Легкий шоколадный мусс-торт', 16.00, 'desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 4.8, true),
('Oq shokoladli tort', 'White Chocolate Cake', 'Торт из белого шоколада', 'Oq shokolad bilan shirinlik', 'Sweet cake with white chocolate', 'Сладкий торт с белым шоколадом', 17.50, 'desserts', 'https://images.unsplash.com/photo-1548907040-4baa42d10919', 4.7, true),
('Espresso tort', 'Espresso Cake', 'Эспрессо торт', 'Qahva ta''mi bilan tort', 'Coffee flavored cake', 'Торт со вкусом кофе', 15.00, 'desserts', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', 4.6, true),
('Yer yong''oqli tort', 'Peanut Cake', 'Арахисовый торт', 'Yer yong''oq bilan tayyorlangan tort', 'Cake made with peanuts', 'Торт приготовленный с арахисом', 14.50, 'desserts', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187', 4.5, true),

-- Ice Creams & Frozen Desserts (10 items)
('Vanil muzqaymoq', 'Vanilla Ice Cream', 'Ванильное мороженое', 'Klassik vanil muzqaymoq', 'Classic vanilla ice cream', 'Классическое ванильное мороженое', 6.00, 'desserts', 'https://images.unsplash.com/photo-1551024506-0bccd828d307', 4.5, true),
('Shokoladli muzqaymoq', 'Chocolate Ice Cream', 'Шоколадное мороженое', 'Boy shokolad ta''mi bilan muzqaymoq', 'Rich chocolate flavored ice cream', 'Богатое шоколадное мороженое', 6.50, 'desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 4.6, true),
('Qulupnayli muzqaymoq', 'Strawberry Ice Cream', 'Клубничное мороженое', 'Yangi qulupnay bilan muzqaymoq', 'Fresh strawberry ice cream', 'Свежее клубничное мороженое', 7.00, 'desserts', 'https://images.unsplash.com/photo-1548907040-4baa42d10919', 4.7, true),
('Pistachio muzqaymoq', 'Pistachio Ice Cream', 'Фисташковое мороженое', 'Pista bilan tayyorlangan muzqaymoq', 'Ice cream made with pistachios', 'Мороженое приготовленное с фисташками', 8.00, 'desserts', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', 4.8, true),
('Karamel muzqaymoq', 'Caramel Ice Cream', 'Карамельное мороженое', 'Shirin karamel ta''mi bilan muzqaymoq', 'Sweet caramel flavored ice cream', 'Сладкое карамельное мороженое', 6.50, 'desserts', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187', 4.5, true),
('Mango sorbet', 'Mango Sorbet', 'Манго сорбет', 'Tropik mango bilan tayyorlangan sorbet', 'Tropical mango sorbet', 'Тропический манго сорбет', 7.50, 'desserts', 'https://images.unsplash.com/photo-1551024506-0bccd828d307', 4.6, true),
('Limon sorbet', 'Lemon Sorbet', 'Лимонный сорбет', 'Yangi limon bilan sorbet', 'Fresh lemon sorbet', 'Свежий лимонный сорбет', 7.00, 'desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 4.4, true),
('Kokteyl muzqaymoq', 'Mixed Berry Ice Cream', 'Ягодное мороженое', 'Aralash rezavorlar bilan muzqaymoq', 'Ice cream with mixed berries', 'Мороженое со смешанными ягодами', 7.50, 'desserts', 'https://images.unsplash.com/photo-1548907040-4baa42d10919', 4.7, true),
('Kok muzqaymoq', 'Coconut Ice Cream', 'Кокосовое мороженое', 'Kokos ta''mi bilan muzqaymoq', 'Coconut flavored ice cream', 'Кокосовое мороженое', 6.50, 'desserts', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', 4.5, true),
('Muzli sharbat', 'Frozen Sherbet', 'Замороженный шербет', 'Sovuq sharbat shirinligi', 'Cold sherbet dessert', 'Холодный десерт шербет', 6.00, 'desserts', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187', 4.3, true),

-- Pastries & Cookies (10 items)
('Frenk kruassani', 'French Croissant', 'Французский круассан', 'Yog''li Fransuz kruassani', 'Buttery French croissant', 'Масляный французский круассан', 5.50, 'desserts', 'https://images.unsplash.com/photo-1551024506-0bccd828d307', 4.6, true),
('Eklari', 'Cream Eclair', 'Эклер со сливками', 'Krem bilan to''ldirilgan ekler', 'Eclair filled with cream', 'Эклер наполненный кремом', 4.50, 'desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 4.5, true),
('Shokoladli kuyki', 'Chocolate Cookies', 'Шоколадное печенье', 'Shokolad bo''laklari bilan kuyki', 'Cookies with chocolate chips', 'Печенье с шоколадными чипсами', 3.50, 'desserts', 'https://images.unsplash.com/photo-1548907040-4baa42d10919', 4.4, true),
('Yong''oqli kuyki', 'Nut Cookies', 'Ореховое печенье', 'Turli yong''oqlar bilan kuyki', 'Cookies with various nuts', 'Печенье с различными орехами', 4.00, 'desserts', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', 4.3, true),
('Kanele', 'French Canele', 'Французские канеле', 'Fransuz kanele shirinligi', 'French canele pastry', 'Французская выпечка канеле', 6.00, 'desserts', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187', 4.7, true),
('Makarun', 'French Macarons', 'Французские макаруны', 'Rangli Fransuz makarunlari', 'Colorful French macarons', 'Цветные французские макаруны', 8.00, 'desserts', 'https://images.unsplash.com/photo-1551024506-0bccd828d307', 4.8, true),
('Madlen', 'Madeleine Cakes', 'Печенье мадлен', 'Kichik madlen kekslari', 'Small madeleine cakes', 'Маленькие пирожные мадлен', 5.00, 'desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 4.5, true),
('Daniyal pechi', 'Danish Pastry', 'Датская выпечка', 'Daniyal uslubidagi xamir', 'Danish style pastry', 'Выпечка в датском стиле', 5.50, 'desserts', 'https://images.unsplash.com/photo-1548907040-4baa42d10919', 4.4, true),
('Pishiriq ruleti', 'Pastry Roll', 'Рулет из теста', 'Shirinlik bilan o''ralgan rulet', 'Sweet filled pastry roll', 'Сладкий рулет с начинкой', 4.50, 'desserts', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', 4.3, true),
('Beze', 'Meringue', 'Безе', 'Tuxum oqidan tayyorlangan beze', 'Meringue made from egg whites', 'Безе приготовленное из яичных белков', 3.00, 'desserts', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187', 4.2, true),

-- Special & Exotic Desserts (5 items)
('Baklava', 'Turkish Baklava', 'Турецкая пахлава', 'Asal va yong''oq bilan baklava', 'Baklava with honey and nuts', 'Пахлава с медом и орехами', 9.50, 'desserts', 'https://images.unsplash.com/photo-1551024506-0bccd828d307', 4.9, true),
('Kunjalik halva', 'Sesame Halva', 'Кунжутная халва', 'Kunjut urug''idan tayyorlangan halva', 'Halva made from sesame seeds', 'Халва приготовленная из кунжута', 8.50, 'desserts', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587', 4.6, true),
('Rahat lukum', 'Turkish Delight', 'Рахат-лукум', 'Turkcha rahat lukum shirinligi', 'Turkish delight confection', 'Турецкие рахат-лукум', 7.00, 'desserts', 'https://images.unsplash.com/photo-1548907040-4baa42d10919', 4.5, true),
('Gujiya', 'Sweet Dumpling', 'Сладкие пельмени', 'Shirinlik bilan to''ldirilgan gujiya', 'Sweet filled dumplings', 'Сладкие пельмени с начинкой', 6.50, 'desserts', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add', 4.4, true),
('Falooda', 'Rose Falooda', 'Фалуда с розой', 'Atirgul ta''mi bilan falooda', 'Falooda with rose flavor', 'Фалуда со вкусом розы', 8.00, 'desserts', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187', 4.7, true);
