// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhnxpvixlaatqqpepyip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impobnhwdml4bGFhdHFxcGVweWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzA4NTMsImV4cCI6MjA2MzY0Njg1M30.1-s9EaljM_nWdFsGTafetLUPe9A8RplNTKAV6X1jXe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);